engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- "yandex_cash_register/locale/"
- "yandex_cash_register/migrations/"
- "yandex_cash_register/templates/"
- "yandex_cash_register/tests/"
