engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_fingerprints:
    - 48c84bda43e6d374efbad461e12c7bea
    - 97ca67773a60917eac1fcc35a7f82f31
    - 5d41272a7cb18818780dbb6bca491f00
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- "yandex_cash_register/locale/"
- "yandex_cash_register/migrations/"
- "yandex_cash_register/templates/"
- "yandex_cash_register/tests/"
