language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION="<1.9"
  - DJANGO_VERSION="<1.10"
  - DJANGO_VERSION=">=1.10"
install: pip install -q "Django$DJANGO_VERSION" lxml
script: coverage run yandex_cash_register/tests/runtests.py
after_script:
  - codeclimate-test-reporter < lcov.info
addons:
  code_climate:
    repo_token: 4075824d95cf41c31d7a059027a4ec2721dfb4f5242f192480ba6c88535aafee
